name: Build APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.9"

      - name: Compilar APK
        run: gradle assembleDebug

      - name: Renomear APK da versão
        run: cp app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/OrbisWatchLab-v0.13-debug.apk

      - name: Publicar APK
        uses: actions/upload-artifact@v4
        with:
          name: OrbisWatchLab-v0.13
          path: app/build/outputs/apk/debug/OrbisWatchLab-v0.13-debug.apk
